(uiop:define-package #:lw2.schema-types
    (:use #:cl #:lw2.schema-type))

(in-package #:lw2.schema-types)

(define-schema-type :post ()
  ((post-id string :alias :--id)
   (title string)
   (user-id string)
   (url (or null string))
   (posted-at string)
   (base-score fixnum)
   (comment-count (or null fixnum))
   (page-url (or null string))
   (word-count (or null fixnum))
   (frontpage-date (or null string))
   (curated-date (or null string))
   (meta boolean)
   (af boolean :backend-type backend-alignment-forum)
   (draft boolean)
   (question boolean :backend-type backend-q-and-a)
   (vote-count (or null fixnum))
   (tags list :graphql-ignore t)
   (html-body (or null string) :qualifier :body)))
